### ISSUE TITLE
Notification banner shows even if you're inside the chat

### ISSUE THREAD

**Issue by jamoness** [signal-csharp/Signal-Windows#138]
Sometimes it doesn't show in or out the app!

**Comment by Trolldemorted** [comment]
The notification logic is pretty dumb, since it depends on #42. I will try to focus on that the next few days.

The banner and sound should (at the moment) fire if a direct message arrives. The only time it should not fire is when a synced sent message arrives, i.e. a message that you sent to someone else on a sibling device.

What notification behaviour do we want (apart from the obvious "respect that the conversation is muted")?

I'd say we should always fire on direct messages, unless the window that currently has focus has the conversation selected and is scrolled to the bottom.

**Comment by Trolldemorted** [comment]
Do you build Signal-Windows yourself? If yes you could test the [readmessages branch](https://github.com/signal-csharp/Signal-Windows/tree/readmessages).

**Comment by Trolldemorted** [comment]
Are you content with 0.2.6?
